### ISSUE TITLE
Sorry, but we’re having trouble signing you in.... 

### ISSUE THREAD

**Issue by aidelbaum** [OfficeDev/Office-365-REST-API-Explorer#3]
I now this is know issue but thought I would share my situation to see if it helps resolve the issus

I have tried my    <maindomain>.sharepoint.com and got the AADSTS70001 error.
the site is the root sharepoint and I have the correct identity settings on my workstation to show my ID etc.

contacted MSFT and they could not see the correlation ID in the logs 

App does get initialized on the SP server and I tried numerous attempts at adding more privileges etc.

then I tried another round on my MSFT MSDN account pointing to the MSFT developer server .  Unfortunately the same problem.

I have pasted the error below.  Let me know if there is anything else I can so to help.

thx

Additional technical information: 
Correlation ID: e96a5fc4-5ca9-4508-9130-99d0f563ef8a 
Timestamp: 2015-07-01 09:56:05Z 
AADSTS70001: Application with identifier a6fd3d58-e820-4e38-93b4-92743e4a572fa6fd3d58-e820-4e38-93b4-92743e4a572f was not found in the directory MYDOMAIN.onmicrosoft.com

**Comment by ricalo** [comment]
Hi @aidelbaum,

Thanks for trying the code sample.
I just reproduced the error. Let me take a closer look and I'll get back to you.

**Comment by ricalo** [comment]
@aidelbaum 
I updated the project. There was a problem with the configuration file App.xaml.
You can clone the repo again and register your app with Add -> Connected Service and give 'Have full control of all site collections'
Or you can go to your App.xaml file and you'll see that the ClientID resource key has a really long value. If you look carefully, you'll note that the value was added twice to the resource key. Like this:

```
<x:String x:Key="ida:ClientID">12345678-1234-1234-1234-12345678<the duplication begins here>12345678-1234-1234-1234-12345678</x:String>
```

Just delete the duplicated value. Let me know if this works

**Comment by aidelbaum** [comment]
Ricardo:

That fixed the problem.

Thank you for your help and the amazing sample project.

M

**Comment by ricalo** [comment]
Thank you for trying it!
