### ISSUE TITLE
Cannot connect to the service  - Connected services configuration failure .

### ISSUE THREAD

**Issue by hernandoz** [OfficeDev/Office-365-REST-API-Explorer#4]
Hi,  I get this error when I enter my O365 tenant , I have connected to my O365 using the connected services  .
I am using VS2015 , W 8.1 pc

**Comment by hernandoz** [comment]
error : Exception of type Microsoft.Office365.OAuth.MissingConfigurationValueException

**Comment by ricalo** [comment]
I just been able to reproduce this error. Let me take a closer look.

**Comment by ricalo** [comment]
There was an extra trailing "/" in the authority URL that previous ActiveDirectory libraries didn't seem to care about. Just removed that and got it working. Let me know if you still run into issues, @hernandoz

**Comment by hernandoz** [comment]
Hi , Is working now , I found a new bug , when sending a post or get I get this error, SelectedItem is NULL ..  SplitPlage.xaml.cs line 316

var selectedItem = (DataItem)itemsViewSource.View.CurrentItem;
                selectedItem.Response = await DataSource.GetResponseAsync(selectedItem.Request);

**Comment by ricalo** [comment]
Mmm... before trying to repro, could you do the following?
- From the start menu in Windows, uninstall the app.
- From the build menu in VS, choose **Clean solution**.

I'll try to repro this later today and I'll open a new issue if this doesn't work for you.

**Comment by hernandoz** [comment]
Hi , I tried that but is not working.

**Comment by ricalo** [comment]
Ok, I'll try to repro in a clean machine.
I'll open a new bug to keep things separate.
