### ISSUE TITLE
SelectedItem is NULL

### ISSUE THREAD

**Issue by ricalo** [OfficeDev/Office-365-REST-API-Explorer#6]
Opening this bug to address @hernandoz comments on issue #4...

``` csharp
SelectedItem is NULL .. SplitPlage.xaml.cs line 316

var selectedItem = (DataItem)itemsViewSource.View.CurrentItem;
selectedItem.Response = await DataSource.GetResponseAsync(selectedItem.Request);
```

@hernandoz, while I'm trying to repro, could you provide more details? Maybe repro steps and what version of Visual Studio you are using?

Thank you!

Update: Unfortunately I couldn't repro in a clean machine. Please check that you have all permissions for Sites and Sign you in and read your profile for Users and Groups.

**Comment by hernandoz** [comment]
Hi @Ricalo , I am using W8.1 and latest version of VS2015 , run the app , connect to your O365 Domain and try to create a list, click send.

**Comment by hernandoz** [comment]
@Ricalo I just check the permission and is all correct , see screenshot below 
![error](https://cloud.githubusercontent.com/assets/1914468/12529831/d1b3a888-c1be-11e5-9fdd-1bce03740ac0.JPG)

I am log in as the Admin , so I do have permission to create list.

Thanks for your help .

**Comment by hernandoz** [comment]
Hi quick question , Do I need to enter any values on the header or body , before I press send ?

**Comment by ricalo** [comment]
The values in the header and body and endpoint should be prepopulated for you using the data in the [InitialData.json](https://github.com/OfficeDev/Office-365-REST-API-Explorer/blob/master/Office365RESTAPIExplorer/DataModel/InitialData.json) file. 

This is what you should see right before pressing **Send**.
![2016-01-25_10-20-46](https://cloud.githubusercontent.com/assets/989368/12560187/226d3862-c34e-11e5-8ce0-7b7b2f2cdf56.png)

Also, it seems like you have an older version of the sample. Line 317 doesn't match the latest version in this repo. Could you pull the latest changes and try again?

**Comment by hernandoz** [comment]
something is not working my header and body are not populate with any data 
![restcapture](https://cloud.githubusercontent.com/assets/1914468/12564948/09d5e680-c3aa-11e5-85bc-e0ed87452a3d.JPG)

I just downloaded the repro again and same as before. , see screenshot attached .

thanks

**Comment by ricalo** [comment]
Mmm... I've seen that error before. It happens to me when I use the newer versions of **Newtonsoft.Json**. Funny thing is I don't know how that NuGet package got updated in your download.

Here is a comparison of the sample using Newtonsoft.Json version 8.0.2 (left) versus 6.0.5 (right)
![2016-01-25_10-20-46](https://cloud.githubusercontent.com/assets/989368/12589575/46a36326-c413-11e5-8fd1-c7ffb3363708.png)

I think you can just right-click the project on Visual Studio, select **Manage NuGet Packages...**, scroll down to **Newtosoft.Json** and update to version **6.0.5**.

Let me know if this helps.

**Comment by hernandoz** [comment]
Great, I changed the Newtosoft.Json to 6.0.5 and it is working now.

Thanks for your help .

**Comment by ricalo** [comment]
Awesome, thank you for trying this sample.
